namespace SourceLib.Core.Formats.MDL;

[Flags]
public enum StudioMdlFlags
{
    AutogeneratedHitbox = 0x00000001,
    UsesEnvCubemap = 0x00000002,
    ForceOpaque = 0x00000004,
    TranslucentTwopass = 0x00000008,
    StaticProp = 0x00000010,
    UsesFbTexture = 0x00000020,
    HasShadowLod = 0x00000040,
    UsesBumpmapping = 0x00000080,
    UseShadowLodMaterials = 0x00000100,
    Obsolete = 0x00000200,
    Unused = 0x00000400,
    NoForcedFade = 0x00000800,
    ForcePhonemeCrossfade = 0x00001000,
    ConstantDirectionalLightDot = 0x00002000,
    FlexesConverted = 0x00004000,
    BuiltInPreviewMode = 0x00008000,
    AmbientBoost = 0x00010000,
    DoNotCastShadows = 0x00020000,
    CastTextureShadows = 0x00040000,
    VertAnimFixedPointScale = 0x00200000,
}
